---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# PCAone algorithms in R with RcppEigen!

<!-- badges: start -->
<!-- badges: end -->


## Installation

You can install the development version of PCAoneR from [GitHub](https://github.com/) with:

``` r
install.packages("devtools") # if not installed
devtools::install_github("Zilong-Li/PCAoneR")
```

## Example

This is a basic example which shows you how to use pcaone:

```{r example}
library(pcaone)
mat <- matrix(rnorm(100*20000), 100, 20000)
res <- pcaone(mat, k = 10)
str(res)
```

## Benchmarking

Let's see the performance of ```pcaone``` compared to the other rsvd packages

```{r}
library(microbenchmark)
library(pcaone)
library(rsvd)
data(tiger)
timing_svd <- microbenchmark(
    'SVD' = svd(tiger, nu=150, nv=150),
    'rSVD' = rsvd(tiger, k=150),
    'pcaone.alg1' = pcaone(tiger, k=150, method = "alg1"),
    'pcaone.alg2' = pcaone(tiger, k=150),
    times=10)
print(timing_svd, unit='s')
```

