# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' one pass randomized svd in PCAone, modified from Yu et al 2017.
#' @param mat the input matrix.
#' @param k top k singular values, k << any(dim(mat)).
#' @param l oversampling.
#' @param p number of power iterations.
#' @param rand distribution of random matrix. 1: standard noraml distribution. 2: uniform distribution
#' @export
PCAoneY <- function(mat, k, l = 10L, p = 3L, rand = 1L) {
    .Call(`_PCAoneR_PCAoneY`, mat, k, l, p, rand)
}

