# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title The one pass randomized svd in PCAone, modified from Yu et al 2017.
#' @param mat the input matrix.
#' @param k top k singular values, k << any(dim(mat)).
#' @param p number of power iterations.
#' @param q oversampling.
#' @param rand distribution of random matrix. 1: standard noraml distribution. 2: uniform distribution
#' @export
PCAoneY <- function(mat, k, p = 3L, q = 10L, rand = 1L) {
    .Call(`_pcaone_PCAoneY`, mat, k, p, q, rand)
}

